[versions]
fabric_loom = "1.12-SNAPSHOT"

minecraft = "1.21.10"
parchment = "2025.10.12"

fabric_loader = "0.17.3"
fabric_api = "0.138.0+1.21.10"

mojank = "1.0.0-SNAPSHOT2"

[plugins]
fabric_loom = { id = "fabric-loom", version.ref = "fabric_loom" }

[libraries]
minecraft = { group = "mojang", name = "minecraft", version.ref = "minecraft" }
parchment = { group = "org.parchmentmc.data", name = "parchment-1.21.10", version.ref = "parchment" }

mojank = { group = "dev.spiritstudios", name = "mojank", version.ref = "mojank" }

fabric_loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric_loader" }
fabric_api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric_api" }
